### ISSUE TITLE
_multiPartFooter Returning Function Instead of String

### ISSUE THREAD

**Issue by kruchone** [form-data/form-data#107]
Should _multiPartFooter be returning a Function? _multiPartHeader functions as I would expect.

Here is the printed _streams array, and you can see the function gets stringified:
`_streams:
   [ '----------------------------825868152491961295908473\r\nContent-Disposition: form-data; name="locations"\r\n\r\n',
     '96683cc9126741d1',
     [Function],
     '----------------------------825868152491961295908473\r\nContent-Disposition: form-data; name="line_item_id"\r\n\r\n',
     '2f5vr',
     [Function] ],`

https://github.com/felixge/node-form-data/blob/0.2/lib/form_data.js#L40

**Comment by alexindigo** [comment]
Can you elaborate on the issue and maybe provide some code for better understanding. Thank you.

**Comment by alexindigo** [comment]
Closing. Let me know if you have further questions.
