### ISSUE TITLE
404 when specifying host, and path in first argument of form.submit

### ISSUE THREAD

**Issue by erikmellum** [form-data/form-data#117]
var form = new FormData();
      form.append('name', project.name);
      form.append('description', 'blerg');
      form.append('project_id', project.notableProject.id);
      form.submit({
        host: 'http://host.notable.dev',
        path: '/api/v1/prototypes',
        headers: {
          'Authentication': 'secret'
        }
      }, function(err, res) {
        if(err) console.log("ERR: ", err)
        else console.log("RES: ", res)
        console.log(res.statusCode);
      });

Will return a 404 even though I can hit that host/path by using submit with the less explicit syntax and get an http 200 (success).

    form.submit('http://host.notable.dev/api/v1/prototypes', function(err, res) {
        if(err) console.log("ERR: ", err)
        else console.log("RES: ", res)
        console.log(res.statusCode);
      });

If more details will help I will be happy to provide them.

**Comment by alexindigo** [comment]
This part should be more like:

```
{
    host: 'host.notable.dev',
    path: '/api/v1/prototypes',
    headers: {
      'Authentication': 'secret'
    }
  }
```

There is separate property for the protocol.

```
{
    protocol: 'http:',
    host: 'host.notable.dev',
    path: '/api/v1/prototypes',
    headers: {
      'Authentication': 'secret'
    }
  }
```

But `http` is the default one, so you can omit it.

**Comment by DylanPiercey** [comment]
I think this is resolved? @erikmellum Does that work for you?

**Comment by alexindigo** [comment]
@erikmellum Please let us know if you have follow up questions. Closing for now.
