### ISSUE TITLE
Why doesn't the request body look 'normal'?

### ISSUE THREAD

**Issue by erikmellum** [form-data/form-data#119]
My form code: 

    var form = new FormData();

    form.append(project.name+'.zip', fs.createReadStream("/"+project.name+'.zip'));
    form.submit({
        host: 'http://host.mysite.dev',
        path: '/api/v1/prototypes',
        headers: {
          'Authentication': 'secret'
        }
      }, function(err, res) {
        if(err) console.log("ERR: ", err)
        else console.log("RES: ", res)
        console.log(res.statusCode);
      });

My backend is expecting the request to look like this (tested with postman).

    ------WebKitFormBoundarywo69VE86H8vMc9ah
    Content-Disposition: form-data; name="attachment"; filename="basic.zip"
    Content-Type: application/zip

    ------WebKitFormBoundarywo69VE86H8vMc9ah--
Instead, my request looks like this crazyness which rails can't interpret as a file. I have no idea how to make a normal multipart form request with node.
    
    {
    "attachment":{
      "_overheadLength":157,
      "_valueLength":0,
      "_lengthRetrievers":[
         null
      ],
      "writable":false,
      "readable":true,
      "dataSize":0,
      "maxDataSize":2097152,
      "pauseStreams":true,
      "_released":false,
      "_streams":[
         "----------------------------860185489573893683941879\r\nContent-Disposition: form-data; name=\"app.zip\"; filename=\"app.zip\"\r\nContent-Type: application-zip\r\n\r\n",
       {
            "source":{
               "_readableState":{
                  "objectMode":false,
                  "highWaterMark":65536,
                  "buffer":[
                     {
                        "type":"Buffer",
                        "data":[
                           80,
                           181
                        ]
                     }
                  ],
                  "length":65536,
                  "pipes":null,
                  "pipesCount":0,
                  "flowing":false,
                  "ended":false,
                  "endEmitted":false,
                  "reading":false,
                  "sync":false,
                  "needReadable":false,
                  "emittedReadable":true,
                  "readableListening":false,
                  "defaultEncoding":"utf8",
                  "ranOut":false,
                  "awaitDrain":0,
                  "readingMore":false,
                  "decoder":null,
                  "encoding":null
               },
               "readable":true,
               "domain":null,
               "_events":{

               },
               "_eventsCount":3,
               "path":"/Users/guest/Library/Application Support/foundation-apps-template/app.zip",
               "fd":299,
               "flags":"r",
               "mode":438,
               "autoClose":true
            },
            "dataSize":0,
            "maxDataSize":null,
            "pauseStream":true,
            "_maxDataSizeExceeded":false,
            "_released":false,
            "_bufferedEvents":[

            ],
            "_events":{

            },
            "_eventsCount":1
         },
         null
      ],
      "_currentStream":null,
      "_boundary":"--------------------------860185489573893683941879"
     }
    }

**Comment by DylanPiercey** [comment]
This seems like you are trying to cast the FormData instance to JSON? Did you figure this one out?

**Comment by alexindigo** [comment]
It's stream object, with added FormData private properties.

And you don't need to have protocol in the host field (remove `http://`).

And to print response from the server, do following:

```
res.on('data', function(data) {
  console.log('res-chunk:', data.toString('utf8'));
});
```

**Comment by alexindigo** [comment]
Oh and your filename path starts with `/`, are you sure you have your file in the specified path?

**Comment by DylanPiercey** [comment]
@alexindigo close this until we here otherwise?

**Comment by alexindigo** [comment]
Yep.

@erikmellum feel free to add more details and reopen the issue if you want to continue this discussion. Thank you.

**Comment by farantesrodrigues** [comment]
Hi guys, I bumped into this discussion while debugging an integration with Tableau REST API. I also was expecting to see a text body request instead of a stream. I fear this is what might be causing my request not to be accepted in the API (all rest seems to be formatted fine). Is there anyway we can avoid using stream/buffers to chunk the data being passed in the request ?
