### ISSUE TITLE
Add node-fetch example to documentation.

### ISSUE THREAD

**Issue by DylanPiercey** [form-data/form-data#131]
Since https://github.com/bitinn/node-fetch/pull/31 it is very easy to use node-fetch with form-data.
I think it would be good to add an example of using node-fetch with node-form-data.

```javascript
// post with form-data (Taken from https://github.com/bitinn/node-fetch/blob/master/README.md)

var FormData = require('form-data');
var form = new FormData();
form.append('a', 1);
fetch('http://httpbin.org/post', { method: 'POST', body: form })
    .then(function(res) {
        return res.json();
    }).then(function(json) {
        console.log(json);
    });
```

I would create a PR but I am unsure where exactly this would be best placed in the docs, or if it should at all.

**Comment by alexindigo** [comment]
Great idea. Alternative submissions would be the good place. You can add it before Notes section. Thank you.
