### ISSUE TITLE
How to add a directory recursively

### ISSUE THREAD

**Issue by Dignifiedquire** [form-data/form-data#149]
I'm looking into uploading a whole directory, e.g.
```
-- test
  |- bar
  |- baz
  | |- b
  | `-f
  `- foo
```
using multipart uploads, so that the resulting request looks something like this:

```
Content-Disposition: form-data: name="files"
Content-Type: multipart/form-data; boundary=--boundary1--

---boundary1--
Content-Disposition: form-data; name="file"; filename="test"
Content-Type: multipart/mixed; boundary=--boundary2--

----boundary2--

Content-Disposition: file; filename="test%2Fbar"
Content-Type: application/octet-stream

<content of bar>

----boundary2--

Content-Disposition: file; filename="test%2Fbaz"
Content-Type: multipart/mixed; boundary=--boundary3--

----boundary3--

Content-Type: application/octet-stream
Content-Disposition: file; filename="test%2Fbaz%2Fb"

<content of b>

----boundary3--
Content-Disposition: file; filename="test%2Fbaz%2Ff"
Content-Type: application/octet-stream

<content of f>

----boundary3----

----boundary2--
Content-Disposition: file; filename="test%2Ffoo"
Content-Type: application/octet-stream

<content of foo>

----boundary2----


----boundary1----
```

while ideally having an API like this: 

```js
form.append('files', 'path/to/test', {recursive: true})
```

I know this is not possible at the moment, but do you have any suggestions on how this could be best achieved, or if this is even a feature you would consider adding? Thanks.

**Comment by simov** [comment]
You can easily implement that in your application layer. Why do you think that recursive file system operations have something to do with a module that generates multipart/form-data bodies?

**Comment by Dignifiedquire** [comment]
I'm sorry this was mostly issues in my application code.  

There is one thing I would need from this library though. I'm tring to pass a path as filename as my server expects that, but it always gets stripped via path.basename. So I was wondering if there could be an option so I could pass in a filename without it being modified before sent.

**Comment by simov** [comment]
I'm not sure if that's part of the `multipart/form-data` spec. However you can use a more generic multipart type like `multipart/related` for example. Take a look [here](https://github.com/request/request#multipartrelated).

So for example you can use it to build your own `form-data` implementation:

```js
multipart: [
  {
    'Content-Disposition': 'file; filename="/path/to/cat.png"'
    'Content-Type': 'image/png',
    body: fs.createReadStream('/path/to/cat.png')
  },
  {
    'Content-Disposition': 'file; filename="/path/to/coffee.jpg"'
    'Content-Type': 'image/jpg',
    body: fs.createReadStream('/path/to/coffee.jpg')
  }
  // ...
]
```

Basically you need to walk recursively through your directory and `push` each file into `Array`. Then pass that array to the request's `multipart` option to upload the files. On the server I'm pretty sure that something like [formidable](https://www.npmjs.com/package/formidable) can parse the multipart body stream for you.

**Comment by Dignifiedquire** [comment]
Thanks for the quick reply, I will try that.

**Comment by simov** [comment]
@Dignifiedquire there you go:

```js
var fs = require('fs')
var path = require('path')
var http = require('http')
var formidable = require('formidable')
var recursive = require('recursive-fs')
var request = require('request')
var mime = require('mime-types')

var src = '/absolute/path/to/src'


// server

var server = http.createServer()
server.on('request', function (req, res) {
  if (req.url == '/upload') {
    var form = new formidable.IncomingForm()
    
    form.parse(req, function (err, fields, files) {})
    form.onPart = function (part) {
      var fpath = part.name.replace('src', 'dest')
      part.pipe(fs.createWriteStream(fpath))
    }
    form.on('end', function () {
      res.end('END')
    })
  }
})
server.listen(3000, function () {
  
  // client

  recursive.readdirr(src, function (err, dirs, files) {
    var body = files.map(function (file) {
      return {
        'Content-Disposition': [
          'form-data;',
          'name="' + file + '"',
          'filename="' + path.basename(file) + '"'
        ].join(' '),
        'Content-Type': mime.lookup(file),
        body: fs.createReadStream(file)
      }
    })
    
    request({
      method: 'POST',
      url: 'http://localhost:3000/upload',
      multipart: body
    }, function (err, res, body) {
      if (err) console.log(err)
      console.log(body)
    })
  })
})
```

The only place where I cheated was that I recreated the destination directory structure by hand, I'm leaving that final touch to you :)

**Comment by Dignifiedquire** [comment]
![giphy](https://cloud.githubusercontent.com/assets/790842/10863276/1081d01e-7fc8-11e5-9de7-f449873f27ba.gif)
