### ISSUE TITLE
Get http json response

### ISSUE THREAD

**Issue by gitoverflow** [form-data/form-data#153]
How can i access the http body response ?

Thats the code im using right now, but i can't detect a body in the res object.

`value.form.submit(url, function (e, res) {
    deferred.resolve(res);
});`

**Comment by DylanPiercey** [comment]
Submit returns a standard nodejs "http#request". You have to listen for "data" events, buffer the data and parse it yourself (or using a module). Check out https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/ for more info.

**Comment by DylanPiercey** [comment]
Closing this for now, let me know if this didn't help your issue.
