### ISSUE TITLE
Lowercase headers

### ISSUE THREAD

**Issue by andersonlevita** [form-data/form-data#155]
In getHeaders method, headers keys are converted to lowercase. And the api server is case sensitive.

**Comment by mcfedr** [comment]
Http headers are case insensitive according to the spec, you should handle this in your server code. http://stackoverflow.com/a/5259048/859027

**Comment by DylanPiercey** [comment]
@mcfedr is correct. In fact in NodeJS server response headers are always automatically converted to lowercase.

**Comment by mikeal** [comment]
so, the right thing to do here is to *preserve* the casing and still treat headers as caseless. it's surprisingly annoying to do but it's the right approach.

i wrote a module for dealing with this that we now use in request https://www.npmjs.com/package/caseless
