### ISSUE TITLE
SCRIPT5009: 'FormData' is undefined in IE9

### ISSUE THREAD

**Issue by tarikihm** [form-data/form-data#160]
Is this on purpose or am I expected to include another third-party lib to support it on IE9?
I am using Request with Browserify (latest versions), which in turns depends on form-data.

**Comment by alexindigo** [comment]
Hey,

Didn't know `request` works in a browser. :) I thought it's server-side project, and `form-data`  definitely is.
So for browserify we fallback to native browser `FormData` object (this is what it was implemented after).
In your case, something like `es5-shim` (haven't tried myself though) might help to bring old browsers up to speed with modern tech.

Or looks like `es5-shim` isn't enough either, check out this thread:
http://stackoverflow.com/questions/15475215/formdata-in-ie8-9

PS. Do you know what is `request`'s maintainers' take on using it in a browser?
/cc @simov

**Comment by tarikihm** [comment]
Yes, that makes sense, I think it's mostly Browserify's job to ensure the browser compatibility, I just [reported](https://github.com/substack/node-browserify/issues/1474) this bug with them. I think `request` is also mostly or at least initially server-side and Browserify works to ensure it works too in the browser.
