### ISSUE TITLE
add custom Content-Type in formdata

### ISSUE THREAD

**Issue by gexiaowei** [form-data/form-data#162]
formdata version is updated 1.0.0-rc3。when I post multiPart data with Chinese, it will change to digital gibberish because of I can not custom  Content-Type by using request.filed(filed,value)
so I want know If can add a option param like  request.filed(filed,value,option) and this._formdata.append(filed,value,option)

**Comment by alexindigo** [comment]
Hey,

Sorry for the mishap, do you mind to provide example of your code with example data?

Thank you.

**Comment by gexiaowei** [comment]
for example like:
`var FormData = require('form-data');`
`var formData = new FormData();`
`formData.append('barId', barId);`
`formData.append('title',title, {contentType: 'text/plain; charset=UTF-8'});`
`var publicRequest = request.post(url);`
`publicRequest._formData = formData;`
`publicRequest.end`

I want to set the contentType of title 'text/plain; charset=UTF-8' I think it works only by this way
cause `publicRequest.field('title', title)` can not do it 

so do you mind to add a param in `.field` function

**Comment by DylanPiercey** [comment]
This can be done if https://github.com/form-data/form-data/pull/190 lands by doing

```js
formData.append('title', title, { header: { contentType: 'text/plain; charset=UTF-8' } });
```

**Comment by gexiaowei** [comment]
ok thank you so much
