### ISSUE TITLE
Browserify of formdata does not has submit method

### ISSUE THREAD

**Issue by mondwan** [form-data/form-data#201]
Hello,

I have a problem when using this module with browserify. As browser field in `package.json` in this module honors `global.FormData`, however, the [builtin][1] one does not provide implementation for `submit`.

[1]: https://developer.mozilla.org/en/docs/Web/API/FormData

I get an exception from the compiled script about `submit is not a function` as a result.

I am wondering how to tackle this issue? Either overriding behavior of `browser field` or other alternative implementation are welcome.

**Comment by mondwan** [comment]
Similar to tickets in #124 and #139

**Comment by mxr576** [comment]
I have the same problem, I'm trying to browserify the [httpsnippet](https://github.com/Mashape/httpsnippet) library with webpack, which also depends on this module.
@DylanPiercey Can you help us? How can we do this with/without the isomorphic-form-data module?

**Comment by mondwan** [comment]
My solution is sending request with [node-fetch][1] instead of using the `submit()` from form-data.

In my opinion, form-data and node-fetch play well together.

[1]: https://github.com/bitinn/node-fetch

**Comment by DylanPiercey** [comment]
@mondwan That is the correct solution. As of https://github.com/bitinn/node-fetch/commit/ffac4177b0ba969219a65c373eb955cb161c3376 node-fetch will properly use FormData.

Personally I think the "submit" api should be removed as it deviates from creating a server side shim for FormData however this would break a bunch of stuff (as per https://github.com/form-data/form-data/issues/124).

I'm going to close this for now but feel free to ping me if you have any other issues using this module isomorphically.
