### ISSUE TITLE
new standard makes FormData not only writable

### ISSUE THREAD

**Issue by jimmywarting** [form-data/form-data#212]
> The spec was fleshed out to add has(), get(), getAll(), delete(), set(), entries(), keys(), values(), forEach() and Symbol.iterator() methods to allow inspection, iteration and modification.
https://www.chromestatus.com/features/5701572055007232

https://xhr.spec.whatwg.org/#formdata

I believe this is just extended version of [Map](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map) or [Set](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set)

So something along with this (but written in es5?) would be signifiant. Don't have to rewrite everything...

```javascript
class FormData extends Map {
    constructor() {
        super()
    }
}
```

**Comment by DylanPiercey** [comment]
I've updated https://github.com/form-data/form-data/issues/124 to include the new methods. We can continue the discussion there. PR's welcome!
