### ISSUE TITLE
Cannot get the data out of FormData object

### ISSUE THREAD

**Issue by turboza** [form-data/form-data#213]
I want to perform the test against the FormData object but it seems that there is no `FormData.get` method available. 

I read the FormData api from here https://developer.mozilla.org/en/docs/Web/API/FormData. So I wonder why doesn't it has `get` method. How can I get the data from the FormData object?

**Comment by DylanPiercey** [comment]
The #get method for FormData has just been recently added to chrome and firefox. I've updated https://github.com/form-data/form-data/issues/124 which strives for api symmetry with the browser to include these new methods. You can track progress there.

**Comment by turboza** [comment]
Thank you @DylanPiercey for informing. Your lib is very useful for Node. I will be looking forward to see the new release. :)

**Comment by enricovittorini** [comment]
hello all, when do you think it will be possible to do the "get" method to extract data from the FormData?
