### ISSUE TITLE
Address issue found in test/integration/test-http-response.js [Opened by bitHound]

### ISSUE THREAD

**Issue by xaxiclouddev** [form-data/form-data#227]
bitHound discovered 2 DuplicateFunctions in [test/integration/test-http-response.js](https://github.com/form-data/form-data/blob/9b8d70408037272765da4006df30f31b15aa7cfe/test/integration/test-http-response.js). For details go to [bitHound](https://www.bithound.io/github/form-data/form-data/blob/9b8d70408037272765da4006df30f31b15aa7cfe/test/integration/test-http-response.js).

**Comment by alexindigo** [comment]
It's test files and they do have repeating patterns, to increase readability, making tests DRY would over complicated them. Although if you can produce compelling PR that would reduce duplication and won't hurt readability, it will be welcome. Thank you.
