### ISSUE TITLE
Address issue found in lib/form_data.js [Opened by bitHound]

### ISSUE THREAD

**Issue by xaxiclouddev** [form-data/form-data#228]
bitHound discovered 1 TodoComment in [lib/form_data.js](https://github.com/form-data/form-data/blob/ddb3762e4bc582e92e8b3576ef9bf52534aa8631/lib/form_data.js). For details go to [bitHound](https://www.bithound.io/github/form-data/form-data/blob/ddb3762e4bc582e92e8b3576ef9bf52534aa8631/lib/form_data.js).

**Comment by alexindigo** [comment]
Yes, it's a bug in old version of nodejs. After we release 1.0.0 we will drop support of the old node version and will remove that chunk of the code with the corresponding comment. Thank you.
