### ISSUE TITLE
Cann't upload file appended to FormData with fetch 

### ISSUE THREAD

**Issue by wuhaixing** [form-data/form-data#234]
The following code don't work:

``` javascript

const form = new FormData()
const media = "test/images/test.jpg"    
form.append('media',fs.createReadStream(media))

fetch(uploadUrl, {
          method: 'POST',             
          body: form
 })
.then(response => respons.json() ) 
.then(json => {
    console.log(json)
})
```

So, I had to wrap submit into a Promise:

``` javascript

return new Promise(function(resolve,reject) {          
           const form = new FormData()
           const media = "test/images/test.jpg"
           form.append('media',fs.createReadStream(media))           
           form.submit({
                 host:'localhost',
                 path:'/upload?type=image'
               },function(err,res) {
                 if(err) {
                   reject(err)
                 } else {
                   res.on('data',function(chunk) {
                     resolve(JSON.parse('' + chunk))
                   })
                 }
               })
             })
```

BTW,why cann't submit to an url? Why only 

```
{
     host:'localhost',
     path:'/upload?type=image'
}
```

works?

**Comment by DylanPiercey** [comment]
@wuhaixing you are using https://github.com/bitinn/node-fetch or https://github.com/matthew-andrews/isomorphic-fetch right? Also what do you mean by doesn't work? Does it send the request without form data or does it not send the request?

**Comment by mbrevda** [comment]
Not sure if this is related (or if I should open a new issue):
using bitinn/node-fetch:

```js
let form = new FormData()
form.append('foo', fs.createReadStream(filePath))
fetch('https://api.rollbar.com/api/1/sourcemap', {method: 'POST', body: form})
```

Doesn't seem to work on larger files. Is my code correct? It would seem the server doesn't have an issue uploading larger files when using other methods.

**Comment by DylanPiercey** [comment]
@wuhaixing can you confirm this is still the case? This issue is quite old and I am wondering if perhaps you were using an older version of node-fetch? Closing the issue for now though.

@mbrevda I believe the issue you are having is unrelated. Would you mind making a PR or gist with a failing test case and we can look into the issue?
