### ISSUE TITLE
Import on IE9

### ISSUE THREAD

**Issue by Ferossgp** [form-data/form-data#240]
There is any possibility to add support to IE9? Because if I import form-data I get FormData is undefined, and I can't write some alternative only for IE 9

**Comment by alexindigo** [comment]
Hey, thank you for your interest. Although `form-data` is the server-side only library, it never meant to work in any browser. What it does it reimplements FormData native browser API for NodeJS.

Care to provide more information on what you're trying to achieve?

Thank you.

**Comment by DylanPiercey** [comment]
@Ferossgp in the browser this module just supplies the native Form-Data module.

Last I checked there was no good polyfill for form-data that wasn't grotesquely huge and out of scope for this module. I'm going to close this issue for now as there is nothing we can do currently for ie9 short creating a  polyfill.

If you do find a good and reasonably sized polyfill we can consider adding it to this module in the browser.
