### ISSUE TITLE
Abort request

### ISSUE THREAD

**Issue by BesatZardosht** [form-data/form-data#241]
Is there any way to abort a request after submitting the form?
I want to give users the ability to abort an upload after they started it.

**Comment by DylanPiercey** [comment]
@BesatZardosht I don't think you can abort the built in "FormData.submit", however using something like https://github.com/sindresorhus/got you should be able to abort the request.

Let me know if this works for you so I can close the issue :D.

**Comment by BesatZardosht** [comment]
I found out how to abort the request:
```
const request = form.submit(options, (error, response) => {
    // your code here
}
request.abort();
```

Thanks for your reply..

**Comment by DylanPiercey** [comment]
@BesatZardosht awesome good job finding the solution!
