### ISSUE TITLE
RC?

### ISSUE THREAD

**Issue by hueniverse** [form-data/form-data#246]
Just want to point out this has been published as an RC for 5 months now. If there is a reason for this, ignore me, but I have a feeling this was just forgotten... Please consider this a friendly and appreciative ping.

**Comment by alexindigo** [comment]
Yeah. :) Thanks for the ping. We do need to get our stuff together. 

We planned to address this issue for 1.0 – https://github.com/form-data/form-data/issues/133
@DylanPiercey what do you think can we squeeze it in, or leave for later?

**Comment by hueniverse** [comment]
My advice is that versions are cheap and you can always release again. I stopped waiting for that one more issue to close before a release, event a major one.

**Comment by DylanPiercey** [comment]
@alexindigo can you help refresh my memory what was missing from https://github.com/form-data/form-data/pull/190?

**Comment by alexindigo** [comment]
@DylanPiercey Yeah, I don't remember myself. :) Ok, I'll take a look and cut out new version as @hueniverse suggested. I think he is right we did take too long with RCs :)

**Comment by alexindigo** [comment]
Published `v1.0.0`. Thank you.
