### ISSUE TITLE
form-data 2.0 is breaking node-fetch integration

### ISSUE THREAD

**Issue by bitinn** [form-data/form-data#262]
see my original issue #196

form-data didn't provide an API for us to detect `form-data` body contains streamed data or not,  which we need to set headers properly. so we had to resort to checking `_lengthRetrievers.length`.

now with 2.0, this property is renamed and breaks our integration.

ref:
- https://github.com/bitinn/node-fetch/blob/master/index.js#L92-L103

**Comment by alexindigo** [comment]
Hey, sorry I dropped the ball here.
I agree we should add some public API for this thing, somehow I got confused with original proposal as something specific to sync length resolution.

We could add some generic method, that'd be useful in your case as well, like

```
formData.hasKnownLength()
```

But in the same time, I'm curious, why it's trying to use synchronous length resolution, which doesn't cover all use cases, and you'd need to get final length anyway to provide Content-Length http header.

Can you use `formData.getLength(function(err, length){ ... })` ?

Thank you.

**Comment by bitinn** [comment]
> formData.hasKnownLength()

Yeah that would be a good solution, we only need to know if `form-data` object contains streamed sources or not.

> why it's trying to use synchronous length resolution

Because when you use streamed data, the default is to set `transfer-encoding: chunked`, so you don't need a `content-length` header. 

OK, but why not just send everything as `chunked`? Because older servers either don't like it or don't support it. Like WSGI used by Python community.

So it leads us to current implementation.

ref:
- https://github.com/bitinn/node-fetch/issues/47
- https://github.com/bitinn/node-fetch/pull/58

**Comment by alexindigo** [comment]
"Actually" :) With my experiments, most of the servers didn't support chunked uploads (seems like that was mostly implemented in browsers for the response body). Only nodejs based servers handled chunked properly.

And in any rate, sometimes (in my tests most of the time) you'd send streamed data (likes files) to servers that don't support chunked requests. So why not to make async and get the size and send Content-Length to all the servers. Like it's done here: https://github.com/form-data/form-data/blob/master/lib/form_data.js#L402-L416

**Comment by bitinn** [comment]
Browsers will be using chunked encoding in stream mode as well, it's really not a simple choice like that.

And if you are not streaming data (say the remote server doesn't support it), then the problem lays on developers to buffer their content, not for `node-fetch` to do this work silently.

**Comment by alexindigo** [comment]
In most cases you can get size of the stream without much buffering, like files and another http response – you usually can get size of the content before hand. And that `getLength` will do it for you, so there is no extra stuff node-fetch needs to implement. Just change it's API to make it async, which is usually good idea when dealing with I/O. :)

But for sure, I'll implement that other method, just wanted to contribute my two cents into making world a better place :)

**Comment by bitinn** [comment]
> In most cases you can get size of the stream without much buffering

But on the other hand, aren't there scenarios where you just can't know content length?

> But for sure, I'll implement that other method

Thx!

**Comment by bitinn** [comment]
I mean I don't have a good example at hand, those I heard from a few issues on node-fetch and this comment on Fetch Spec: https://github.com/whatwg/fetch/blob/6f223de29733e64dbe1dfc6028c6e0a4a5d89398/Overview.html#L3165

**Comment by alexindigo** [comment]
> But on the other hand, aren't there scenarios where you just can't know content length?

There are always scenarios when something wouldn't work, like they'd give you wrong content-length :) But we're trying to stay positive aren't we? :) And despite/inspite that – Async #AllTheThings! is just a good approach no matter what :)

**Comment by bitinn** [comment]
> Async #AllTheThings

Hey I agree! And `chunked` is async too, just that not many servers out there supports it. To me the better choice would be to not calculate content-length for streams unless it's necessary.

**Comment by alexindigo** [comment]
👍

**Comment by bitinn** [comment]
Cheers!

(I am sure you know this: setting `content-length` will disable `transfer-encoding: chunked`. If we start to calculate and set `content-length` by default, I bet some Node.js devs will come to me one day >_<)

Anyway enjoy your weekend :)

**Comment by alexindigo** [comment]
Yes, I spent some time around chunked encoding. :) 
What I meant by async all the things, is make your API that interacts with I/O async by default, it will allow you for greater flexibility. In your case you'd have choice calculate or not length of the streams, as of now you simply don't have that choice. :)

Here is PR with new method: https://github.com/form-data/form-data/pull/263

**Comment by alexindigo** [comment]
Fixed in v2.1.0
