### ISSUE TITLE
Usage of `self` instead of `window` broken on React Native

### ISSUE THREAD

**Issue by Janiczek** [form-data/form-data#271]
Commit [2c0a54](https://github.com/form-data/form-data/commit/2c0a54532c22da345e85afd559a9c6a14ec8155b) introduced `self` instead of `window` but this breaks in React Native - `self is undefined`. Maybe a different `require` implementation or something...
`window` works (as of v2.1.0).

**Comment by StevePotter** [comment]
Alex, basically in react native there is no self available during load; instead, it provides a global object.  Interestingly though, when you put react native into debug mode, it works.  But you still can't ship apps.  I patched it and submitted the PR.

**Comment by alexindigo** [comment]
Fixed in #282, will publish 2.1.2 after tests pass. Thank you.

**Comment by ballPointPenguin** [comment]
I believe the use of `window` is causing my build to break when using Electron (with react) on MacOS.

**Comment by alexindigo** [comment]
Looks like different environments expect different global objects. And `FormData` isn't meant for any of them. :)

@ballPointPenguin I'm just curious, how did you end up requiring `form-data` in Electron app? :)

**Comment by ballPointPenguin** [comment]
I'm using the `request` module to post form data to an authentication endpoint.

**Comment by alexindigo** [comment]
Thanks for the reply @ballPointPenguin.
`request` is a server side module (same as `form-data`),
so if you're using it within node part of the app, it should work normally.

And it won't work from the browser part of the app. 
In the browser part you could use built-in `fetch` method to communication with the servers.

Does it make sense to you? Or did I miss something?

Thanks.

**Comment by ballPointPenguin** [comment]
That's quite sensible. Thank you.

**Comment by ballPointPenguin** [comment]
In electron, one might do things that are both server-like and client-like.
One thing I'd like to do is use `request` and `form-data` from the server-ish side of things.
Simply including `form-data` in my package.json causes the electron build to fail.

**Comment by ballPointPenguin** [comment]
FWIW this works for me:
https://github.com/codex-digital/form-data/blob/master/lib/browser.js
but feels rather tacky
