### ISSUE TITLE
Support PUT requests

### ISSUE THREAD

**Issue by farantesrodrigues** [form-data/form-data#276]
Maybe I'm missing something, but in

`
    FormData.prototype.submit = function(params, cb) {
      var request,
             options,
             defaults = {method: 'post'};
`

defaults is not configurable, right ?

I have a use case where I need to use PUT requests. It's an integration with Tableau API that only accepts PUT requests... (more info [here](https://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_concepts_publish.htm#multi_part))

**Comment by jimmywarting** [comment]
https://github.com/form-data/form-data/issues/124#issuecomment-124996556

**Comment by alexindigo** [comment]
@farantesrodrigues you should be able to pass `method` property to the submit call.

```javascript
formData.submit({method: 'put'}, callback);
```

Let me know if you have any issues with that.

Thank you.
