### ISSUE TITLE
A tabular format is not the same. When pressing the button add information

### ISSUE THREAD

**Issue by fzjameza** [form-data/form-data#290]
A tabular format is not the same. When pressing the button add information.

`<script type="text/javascript" src="js/jquery.js"></script>` 
`</head>`
`<body>`
`<table width="100%"  border="1" align="center" >`
 `  <tr>`
  `  <td align="left" valign="top">`
  `  <form method="post" action="">`
  `  <div id="form">`
 `   <table width="100%" border="1" cellspacing="0" cellpadding="0">`
     ` <tr>`
        `<td colspan="1" bgcolor="#6699C"><font color="white">ร้านอาหาร</font></td>`
     ` </tr>`
     ` <tr>`
        `<td><input type="checkbox" name="res" value="บาร์บีคิว"/>`
            `<span class="style1"><img src="images/category/ก๋วยเตี๋ยว.png" width="25" height="25">บาร์บีคิว</span></td>`
      `  <td><input type="checkbox" name="res" value="ก๋วยเตี๋ยว"/>
            <span class="style1">ก๋วยเตี๋ยว</span></td>`
       ` <td><input type="checkbox" name="res" value="สเต็ก"/>
            <span class="style1">สเต็ก</span></td>`
        `<td><input type="checkbox" name="res" value="จานด่วน"/>
            <span class="style1">จานด่วน</span></td>`
     `   <td><input type="checkbox" name="res" value="พิซซ่า"/>
            <span class="style1">พิซซ่า</span></td>`
      `  <td><input type="checkbox" name="res" value="เบเกอรี่"/>
            <span class="style1">เบเกอรี่</span></td>`
       ` <td><input type="checkbox" name="res" value="ยำ&ตำ"/>
            <span class="style1">ยำ&amp;ตำ</span></td>`
        `<td><input type="checkbox" name="res" value="ติ่มซำ"/>
            <span class="style1">ติ่มซำ</span></td>`
     ` </tr>`
      `<tr>`
      `  <td><input type="checkbox" name="res" value="สุกี้"/>
            <span class="style1">สุกี้</span></td>`
      `  <td><input type="checkbox" name="res" value="บุฟเฟต์"/>
            <span class="style1">บุฟเฟต์</span></td>`
       ` <td><input type="checkbox" name="res" value="ทะเล"/>
            <span class="style1">ทะเล</span></td>`
      `  <td><input type="checkbox" name="res" value="อื่นๆ"/>
            <span class="style1">อื่นๆ</span></td>`
        `<td>&nbsp;</td>`
      `  <td>&nbsp;</td>`
        `<td>&nbsp;</td>`
        `<td>&nbsp;</td>`
     ` </tr>`
  `  </table>`
    `</div>`
   ` <div id="btnAdd">`
       `<input type="button" value="add information" />`
       `<tr>`
    `   <td colspan="8">`
       ` </td>`
     ` </tr>`
     `</div>`
   ` <table>`
    `  <tr>`
      `  <td><input type="submit"  value="add information" /></td>`
    `    <td>&nbsp;</td>`
        `<td>&nbsp;</td>`
       `<td>&nbsp;</td>`
   `  </tr>     `
`    </table>`
`    </form>`
`    </td>`
`  </tr>`
`  <tr>`
   ` <td bgcolor="#CCC"><b><font size="2" color=blue>Copyright (c) 2010-2014 by Naruepon.p</font></b></td>`
 ` </tr>`
`</table>`

`<script>`

	`$('#btnAdd').click(function() {
      	$('#form').append( "<table width='100%' border='1' cellspacing='0' cellpadding='0'>");
      	$('#form').append( "</tr>");
        $('#form').append( "<td colspan='1' bgcolor='#6699C'><font color='white'>ร้านอาหาร</font></td>");
      	$('#form').append( "</tr>");
      	$('#form').append( "<tr>");
        $('#form').append( "<td><input type='checkbox' name='res' value='บาร์บีคิว' /><span class='style1'><img src='images/category/ก๋วยเตี๋ยว.png' width='25' height='25'>บาร์บีคิว</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='ก๋วยเตี๋ยว' /><span class='style1'>ก๋วยเตี๋ยว</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='สเต็ก' /><span class='style1'>สเต็ก</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='จานด่วน' /><span class='style1'>จานด่วน</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='พิซซ่า' /><span class='style1'>พิซซ่า</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='เบเกอรี่' /><span class='style1'>เบเกอรี่</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='ยำ&ตำ' /><span class='style1'>ยำ&amp;ตำ</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='ติ่มซำ' /><span class='style1'>ติ่มซำ</span></td>");
      	$('#form').append( "</tr>");
      	$('#form').append( "<tr>");
        $('#form').append( "<td><input type='checkbox' name='res' value='สุกี้' /><span class='style1'>สุกี้</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='บุฟเฟต์' /><span class='style1'>บุฟเฟต์</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='ทะเล' /><span class='style1'>ทะเล</span></td>");
        $('#form').append( "<td><input type='checkbox' name='res' value='อื่นๆ' /><span class='style1'>อื่นๆ</span></td>");
        $('#form').append( "<td>&nbsp;</td>");
        $('#form').append( "<td>&nbsp;</td>");
        $('#form').append( "<td>&nbsp;</td>");
        $('#form').append( "<td>&nbsp;</td>");
      	$('#form').append( "</tr>");
      	$('#form').append( "<tr>");
        $('#form').append( "<td colspan='8'>");
        $('#form').append( "</td>");
      	$('#form').append( "</tr>");
    	$('#form').append( "</table>");

      });
</script>
</body>
</html>`

![default](https://cloud.githubusercontent.com/assets/23546596/20418710/ebc74f76-ad82-11e6-8d10-0823d10b17bb.jpg)

**Comment by alexindigo** [comment]
Hi,

Looks like few things got confused here.

`formData.append` is used to add _data_ to the form instance, which later could be sent to the server, not html tags.

And in your example it's jQuery and seems like browser environment. This library is a server side implementation of the in-browser FormData API.

I think you're looking for something like this: http://api.jquery.com/append/
