### ISSUE TITLE
headers params should be Content-Type ,not content-type.

### ISSUE THREAD

**Issue by xiaomingplus** [form-data/form-data#306]
FormData.prototype.getHeaders = function(userHeaders) {
  var header;
  var formHeaders = {
    'Content-Type': 'multipart/form-data; boundary=' + this.getBoundary()
  };

  for (header in userHeaders) {
    if (userHeaders.hasOwnProperty(header)) {
      formHeaders[header.toLowerCase()] = userHeaders[header];
    }
  }

  return formHeaders;
};

please fix..

**Comment by alexindigo** [comment]
Please see this issue: https://github.com/form-data/form-data/issues/155
Thank you.

**Comment by alexindigo** [comment]
I'll close the issue. Please feel free to comment if you have more questions. Thank you.
