### ISSUE TITLE
How can I append multiple files to the same variable?

### ISSUE THREAD

**Issue by stoegerit** [form-data/form-data#319]
I need to feed attach[] form variable for this API https://support.deskpro.com/api/api.html#!/tickets/newTicketAction_post_4.

`        for (var attachment=0; attachment<attachments.length; attachment++) {
          form.append("attach",new Buffer(attachments[attachment],'base64'), {contentType: 'image/png', filename: 'image' + attachment.toString() + '.png'});
        }`

But then only the last image is added.
Where I am going wrong?
Thanks.

**Comment by stoegerit** [comment]
Its actually working as it should, the API side is not processing multiple attachments.

**Comment by buddyp450** [comment]
Could you please clarify? I'm needing this feature as well. Were you able to get it to work or are you saying that the form-data api does not support adding multiple files to a single variable? If not I believe it should seeing as how that's possible using multi-part form data.
