### ISSUE TITLE
Warn if `formData` hash values are not strings, to prevent `source.on is not a function`

### ISSUE THREAD

**Issue by nhooey** [form-data/form-data#321]
In request/request#1495, the example code gets an error like `source.on is not a function` because one of the values in the `formData` has for a `request` or `request-promise` options hash is not a string.

The `form-data` module should detect this error and tell the user to ensure all `formdata` hash values are strings, or `writeStreams`, or whatever else is valid.

**Comment by alexindigo** [comment]
Yeah, looks like legit issue. Do you mind to create a PR? Thank you

**Comment by nhooey** [comment]
@alexindigo That was four months ago. I'm not using the library anymore...

**Comment by alexindigo** [comment]
Ok. I'll close this issue then. :) Thanks.

**Comment by nhooey** [comment]
Why would you close an issue without a solution?

**Comment by alexindigo** [comment]
You said, you're no longer interested in this issue. So it was logical to close it.
Please let me know if/when you want to get back to it. Thank you.

**Comment by nhooey** [comment]
I meant that I can't really make a pull request for it.

It's still an issue potentially to a lot of people, even if they don't complain about it. It's an instance where the code doesn't check its inputs, which is a defect.

**Comment by nhooey** [comment]
I'd suggest leaving it open so we can track the defect.

**Comment by alexindigo** [comment]
Ok.

**Comment by nhooey** [comment]
Thanks @alexindigo!

**Comment by DylanPiercey** [comment]
I'll take a look at this when we do https://github.com/form-data/form-data/issues/137.

**Comment by DylanPiercey** [comment]
Closing as a duplicate of https://github.com/form-data/form-data/issues/137.
Work is being done in https://github.com/form-data/form-data/pull/362.

**Comment by DylanPiercey** [comment]
Also, specifically for converting objects to use formdata syntax see [q-flat](https://github.com/DylanPiercey/q-flat).
