### ISSUE TITLE
using form-data with axios and promises

### ISSUE THREAD

**Issue by tqm-kmd** [form-data/form-data#338]
I have tried using form-data together with axios, in a jasmine test that we are building up, running on nodejs. But can't seem to get a grasp on it

Is there anyone that knows if this is possible?

I would like to use axios, as it is promise based, which standard nodejs http client isn't (afaik)

**Comment by alexindigo** [comment]
I'm not sure what is Axios, but yes, native node things as well as FormData – not promises based.
And in many cases they return Streams. If you need need Promises, you can try one of the callback promise wrappers out there, or create your own.

First hit there, seems like something you might use: https://www.npmjs.com/search?q=callback+promise
