### ISSUE TITLE
Why is Content-Length a required header?

### ISSUE THREAD

**Issue by fabianTMC** [form-data/form-data#341]
I was having an issue where I was handing the FileStream from a http request directly into a form field. The problem was that since I did not know the Content-Length to begin with, the library was automatically using the sum of (overheadLength + lastBoundary length) as the Content-Length which caused the request to fail because the file had not finished streaming. 

This issue disappeared after I had commented out the `request.setHeader('Content-Length', length)` line [here](https://github.com/form-data/form-data/blob/master/lib/form_data.js#L422).

Is there a particular reason why the Content-Length is being set this way. I understand the workaround of the `knownLength` option but it's not always possible to compute.

**Comment by alexindigo** [comment]
Hi,

It's the way HTTP works. Receiving servers need to known length of the content they about to receive, in my cases they have special rules about that, like allowing only content below certain threshold.
There is a possibility of specifying "dynamic" content length, using "transfer-encoding: chunked", but not many servers support it for POST requests yet.

**Comment by fabianTMC** [comment]
Makes sense. I had seen some requests without Content-Length being specified but those were for GET requests so I was confused. Adding `headers: { 'transfer-encoding': 'chunked' }` resolved the issue for me. Thanks for your help.
