### ISSUE TITLE
Protocol field is missing after url parsing

### ISSUE THREAD

**Issue by pinxue** [form-data/form-data#348]
https://github.com/form-data/form-data/blob/master/lib/form_data.js#L388

should be:
options = populate({
      port: params.port,
      path: params.pathname,
      host: params.hostname,
      protocol: params.protocol
    }, defaults);

protocol is missed so far, which cause https url goes wrong.

**Comment by xingyuzhe** [comment]
I found this issue too. This is a serious error since long long ago.

**Comment by alexindigo** [comment]
Looks like real issue. Do you mind to create a PR to fix it? Thank you.

**Comment by luckylooke** [comment]
HTTPS is solved here: https://github.com/form-data/form-data/issues/347#issuecomment-294054239

**Comment by DylanPiercey** [comment]
@pinxue see @luckylooke's answer I believe it should solve your problem.

Closing for now, let me know if the issue persists.
