### ISSUE TITLE
POSTing multipart formdata on existing http2 connection

### ISSUE THREAD

**Issue by Vikaton** [form-data/form-data#350]
## Objective

![image](https://cloud.githubusercontent.com/assets/9522710/25593301/01841da2-2e8a-11e7-8001-9c0f65403b09.png)

How could I achieve sending this multipart form-data over an already existing connection I've made with the API using this library?

**Comment by tmfksoft** [comment]
Hi, Did you find any work around for this? I too am trying to interact with the AVS API. I'm able to get connected, however I cant figure out how to get any data into the body.

**Comment by Vikaton** [comment]
this helped: https://github.com/miguelmota/AVS-server/blob/master/server.js#L131 @tmfksoft

**Comment by tmfksoft** [comment]
Ah thats great, what are you using to handle HTTP2? I've tried the HTTP2 module off npm but I can't for the life of me figure out a way to sent the POST Body. Any method I try fails.

**Comment by Vikaton** [comment]
I'm using `node-spdy` and I'm just using the `.write()` function after I gather all of the info I need to make a request, as in that code I showed
