### ISSUE TITLE
form.submit() to localhost server with all network adapters disabled will hang, when regular AJAX is fine

### ISSUE THREAD

**Issue by CrackAttack** [form-data/form-data#353]
We have an app that uses a node-webkit client and tomcat server, which can be located on the same machine. We've been tracing a bug where sometimes the form.submit() just hangs forever, and finally realized that it happens if (e.g.) a laptop is set to Airplane Mode, or otherwise all network adapters are disabled (including any VMWare virtual adapters, etc).

Our app doesn't care about network adapters (all the AJAX calls to the localhost tomcat server work fine) but it's only the form.submit() that breaks. Any obvious reasons as to why this might be? It'd be nice for this to work in this particular use-case scenario, since it can be quite common for our application....

**Comment by alexindigo** [comment]
I'm not sure how FormData behaves inside node-webkit and in airplane mode :)
I'd assume that ajax calls are coming from within the browser part of your app and FormData operates in the node part. So it might be the difference. Also FormData doesn't handle anything network, it operates on top of native nodejs methods. So it must be nodejs thing.
What you can try though, is to use npmjs.org/request library (there are examples in the readme how to use it with the request lib), maybe it would produce different results.

PS. All our tests are using localhost for connectivity, but we never tried to run them in the Airplane mode (and my laptop doesn't have such mode btw).

So I'm not sure as of nature of the issue nor of the ways to solve it.

**Comment by DylanPiercey** [comment]
@CrackAttack I think this issue is a bit out of scope. If you are using AJAX (IE in the browser) electron or not, you should be using the native FormData implementation, not this. This module is to be used for emulating a form data like api within node js.

Let me know if you disagree, or think I missed the point.

**Comment by CrackAttack** [comment]
Actually I am using it correctly in this instance - we need to use it within node.js (needing to bypass the regular FormData security with sending files without the user needing to specifically select/browse for the files). For us, we use both situations in our app. In one instance, the user will browse for a document and upload it to the (localhost) server using the native implementation, and it works. In a different case, we internally are collecting files to upload to the server without the user needing to browse for them, and we are using this API for node.js to then upload the file(s). In this case, the form-data does not behave like the native one does, and will "hang" when the server is localhost and no active network adapters are present. The native one doesn't have an issue.

All that being said, this is likely close-able, and I think it's useful just having this visible for posterity's sake in case someone else stumbles across it? For us, this specific use-case is relatively rare for our customers (to have both client and server installed on the same PC, and having no active network adapters), and we mitigated this by simply recognizing this scenario, and noting that if the files are on the same PC anyway, we don't need to "upload" them but rather can just browse the local file system for both the client and the server!
