### ISSUE TITLE
Feature request: supplying multiple files through a single append

### ISSUE THREAD

**Issue by buddyp450** [form-data/form-data#358]
Relates to: #319

I have a need to append multiple files to a single 'modules' property based on how I currently use [multer](https://github.com/expressjs/multer).

In app:
```javascript
app.post('/modules/upload', upload.array('modules'), function (req, res, next) {
  // req.files is array of `module` files
})
```

In separate utility:
```javascript
const files = [
  fs.readFileSync(path.resolve(__dirname, 'myFirst.module')),
  fs.readFileSync(path.resolve(__dirname, 'mySecond.module')),
];

const form = new FormData();
form.append('version', '1.0.0');
// This works
// form.append('modules', new Buffer(files[0]), { contentType: 'application/octet-stream', filename: 'myFirst.module' });
// This doesn't
form.append('modules', Buffer.concat(files));
```

If I'm just not using this properly please let me know. Thanks :)

**Comment by buddyp450** [comment]
The [actual spec](https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#interface-formdata) didn't really help me that much. Took me reading the [Mozilla Example for Form Data](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append) for it to click that I could actually append to the same variable multiple times with no fancy hacks needed.

```javascript
formData.append('userpic[]', myFileInput1.files[0], 'chris1.jpg');
formData.append('userpic[]', myFileInput2.files[0], 'chris2.jpg');
```

**Comment by chladnefazole** [comment]
This does not work for me...

Adding to form like this:
````form.append(`blobBuffer[]`, blobsAsBuffers[i], { filename: expressReq.body.files[i].fileName });````

Produces this on the receiving end:
````
{
...
  file: {
    blob: Blob { size: 4168, type: '' },
    fileName: 'file2.txt'
  },
...
}
````

Ie. I try to append 2 files and I only receive the one I appended last
