### ISSUE TITLE
Submit to HTTPS SSL server

### ISSUE THREAD

**Issue by craigbloodworth** [form-data/form-data#370]
Have I just totally missed any mention of this in the docs or is submitting to an SSL secured server not supported using the form.submit method?

If it is could somebody point me in the right direction?

**Comment by alexindigo** [comment]
It works the same way as regular `http:`. In all the examples with `http://`, you can replace it with `https://` and it will work.

One of the examples illustrates how to use it with built in http module, you can do the same but with https module:

```
var https = require('https');

var request = https.request({
  method: 'post',
  host: 'example.org',
  path: '/upload',
  headers: form.getHeaders()
});
```

Also there is integration test that tests https communication:
https://github.com/form-data/form-data/blob/master/test/integration/test-submit-https.js

**Comment by craigbloodworth** [comment]
OK so what you're saying is this example:
```
form.submit('http://example.org/', function(err, res) {
  // res – response object (http.IncomingMessage)  //
  res.resume();
});
```
Would just become...?
```
form.submit('https://example.org/', function(err, res) {
  // res – response object (http.IncomingMessage)  //
  res.resume();
});
```
However how could I also customise the headers in this request?

I need to set a very specific content-type header as well as attach a custom auth header.

**Comment by alexindigo** [comment]
For custom things there are different examples, like this one:
https://github.com/form-data/form-data#alternative-submission-methods

And you can merge your custom headers with the returned data from `form.getHeaders()`.

PS. `content-type` header though should stay the same, since it's multipart/form-data, this what FormData sends to the server.

**Comment by craigbloodworth** [comment]
Thanks so much for your help!

Really appreciated
