### ISSUE TITLE
Form-data throws "ReferenceError: window is not defined" in Webpack bundle

### ISSUE THREAD

**Issue by shcallaway** [form-data/form-data#371]
Form-data does not appear to be compatible with Webpack. I am able to bundle everything using Webpack, but upon running my bundle I encounter a `ReferenceError: window is not defined` exception. 

It is caused by importing this function:

```
/* 459 */
/***/ (function(module, exports) {

/* eslint-env browser */
module.exports = typeof self == 'object' ? self.FormData : window.FormData;
```

I tracked this function to form-data:

```
var FormData = __webpack_require__(459)
```

Commenting out the `module.exports` line above causes the exception to no longer occur.

_I originally opened this issue on the [Request](https://github.com/request/request) page. [More details can be found here.](https://github.com/request/request/issues/2794)_

**Comment by alexindigo** [comment]
Do you mind to elaborate a little bit more on what you're trying to achieve?

Neither `FormData` nor `Request` not meant to be used in the browser – they're nodejs only libraries.
So I'm not sure what benefits you're getting from running them through webpack.

Thank you.

**Comment by shcallaway** [comment]
I am using Webpack with Babel to transpile my code from ES7 to ES6.

**Comment by alexindigo** [comment]
I see. Seems like the best approach would be to tell Webpack to ignore `request` dependency – not to bundle it. Since it'd be in the node_modules anyway and it doesn't need to be transpiled anyway.

**Comment by shcallaway** [comment]
I thought I was doing this, but turns out I was only excluding modules from the Babel loader, and not the entire bundle. Thanks! Sorry for the irrelevant issue. 😳 

For others: The solution I ended up using is described [here](https://stackoverflow.com/a/35820388/6137628).
