### ISSUE TITLE
File not found error is not forwarded through to the piped stream

### ISSUE THREAD

**Issue by kornelski** [form-data/form-data#373]
```js
formData.attach('bad', 'missing file');
formData.pipe(dest);
```

results in an uncaught error. I would expect `FormData` to catch this error and forward it to the destination stream.

This affects superagent: https://github.com/visionmedia/superagent/issues/1305 ([code here](https://github.com/visionmedia/superagent/blob/b2708db533ef5bca394eaaff63f97e485e11f465/lib/node/index.js#L980))

**Comment by niftylettuce** [comment]
Fixed in superagent v7.0.0.

See <https://github.com/visionmedia/superagent/releases/tag/v7.0.0> for more insight.

We've also published this deprecation notice:

```sh
Please upgrade to v7.0.0+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>. Thanks to @shadowgate15 (aka Super Agent Taylor), @spence-s, and @niftylettuce.
```
