### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by harryi3t** [form-data/form-data#375]
On large size form-data object, I get this `maximum stack size exceeded` exception.

```js
var FormData = require('form-data'),
    http = require('http'),
    form = new FormData(),
    request = http.request({
        method: 'post',
        host: 'example.org',
        path: '/upload',
        headers: form.getHeaders()
    });

new Array(1e4).fill(1).forEach(function () {
    form.append('foo', 'bar');
});

form.pipe(request); // Throws RangeError: Maximum call stack size exceeded
```
This module uses the [combined-stream](https://www.npmjs.com/package/combined-stream) module to make itself streamable.

`combined-stream` is [using recursion](https://github.com/felixge/node-combined-stream/blob/master/lib/combined_stream.js#L68) to continuously write data which causes this exception

Note: Originally this issue was [observed](https://github.com/request/request/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+call+stack+size) on [request](https://www.npmjs.com/package/request) module
But I am not sure where this should be fixed.

Linked Issues:
Request: https://github.com/request/request/issues/1561
Combined-Stream: https://github.com/felixge/node-combined-stream/issues/37

**Comment by jmendeth** [comment]
This was fixed in felixge/node-combined-stream#38
