### ISSUE TITLE
Small issue with License and copied code from node-far

### ISSUE THREAD

**Issue by jabeerni** [form-data/form-data#377]
I know this is a nit, but our legal department did a scan of our OSS usage, and found that there is a file in form-data that has basically copied and pasted content from node-far. I believe both code bases were created by Felixge, so I'm not sure it really matters, but I'm not an expert on licensing. I said I'd check to see if anything can (or should) be done to correct this, since technically, forms-data is not in compliance with the MIT License.

File run.js (lines 12–49) contains forensically significant textual similarity to file far.js from the node-far project, "[a] simple test runner that finds and runs multiple node.js files, while providing useful information about output and exit codes." See https://github.com/felixge/node-far. node-far is licensed under the MIT License (see https://github.com/felixge/node-far/blob/master/LICENSE).

Thoughts?

**Comment by alexindigo** [comment]
Hey,

First of all kudos to your legal department :) It's impressive find. 

That said. Yes, test runner was copied from node-far and modified to support istanbul code coverage.
Which is within MIT license boundaries.

Do you mind to elaborate what issues you see in this approach?

Thank you.

**Comment by jabeerni** [comment]
This may be a nevermind issue now. I went back-and-forth with our legal team, and it looks like this was just a warning and not something we have to take action on. I speak better javascript than legalese. There doesn't seem to be enough shared code there to justify a separate package, so please feel free to just close this and get back to doing great things. Sorry for causing any extra worry or work,

**Comment by alexindigo** [comment]
It was a quick hack to get test coverage into the project, but I didn’t feel like that glue and sticks solution is good enough to backport to the original repo. 
If it would be a problem, I think we can wake up Felix and get it backported.

Thanks for going through with this.

Btw, do you know what tool they are using to scan all of github (internet)? :)

**Comment by jabeerni** [comment]
Sorry, not sure what the tool is. I pass a list of all OSS components and versions I'm using to our OSS/Legal folks, and I think they farm it out to a 3rd party that runs the scans. It's both painful and cool at the same time, since I can still spend hours tracking a warning down for something I have no control over... but it does make OSS safer from patent trolls for everyone because devs are actually held accountable for where they get their code.

**Comment by alexindigo** [comment]
Yeah, it's something we all miss in our day jobs, to have that extra step before including yet another library with unknown number of dependencies. :)

Cool. Thanks.
