### ISSUE TITLE
FormData pipe not work with Electron net module

### ISSUE THREAD

**Issue by MCMicS** [form-data/form-data#378]
Hi,
i use the net module from electron because it use advanced logics like proxy handling. (see https://electronjs.org/docs/api/net)

If i start a request and try to pipe formData like in sample no data is written to server.

Steps:
use electron quickstart and add form-data.

```
var FormData = require('form-data');

var form = new FormData({ maxDataSize: 20971520 });
form.append('my_field', 'my value');
form.append('my_buffer', /* something big */);

var net= require('electron').net // or .remote.net if use from renderer;
var request = net.request({
  method: 'post',
  url: 'https://example.org/upload',
  headers: form.getHeaders()
});
debugger
form.pipe(request);

request.on('response', function(res) {
  console.log(res.statusCode);
});

```
if you step into the pipe you see that 'internal/streams/legacy.js' is called und line 15 you see that dest.writable is undefined. I tried an stream.PassThroupgh but with no change in result
```
function ondata(chunk) {
    if (dest.writable) {
      if (false === dest.write(chunk) && source.pause) {
        source.pause();
      }
    }
  }
```
If I pipe a file using readerstream without form-data the server receive the content. But I want to use multpart uploads with net module.
Hope you can help

see related for got module: https://github.com/sindresorhus/got/issues/315

**Comment by edmundogarol** [comment]
@zengdongbao thanks for that. This did it for me. 

`request.writable = true;      // set properties `
