### ISSUE TITLE
FormData submit not a function

### ISSUE THREAD

**Issue by kimwandev** [form-data/form-data#391]
I'm trying to upload a file using form-data and node fs module but it seems that it cannot create the instance of the correct form-data object.

I'm running the app using electron app

![image](https://user-images.githubusercontent.com/16009196/42976368-c2c9e542-8bf3-11e8-9eb1-c668bbc767db.png)

`import * as fData from 'form-data';`
`let form = new fData();`
`let dir = __dirname + '/example.zip'`
`form.append('my_file', fs.createReadStream(dir));`
`form.submit('<WEB_API_SERVICE_POST_URL>', (err, data) => { })`

**Comment by jimmywarting** [comment]
in the browser it form-data is equivalent to `window.FormData` submit is a node-server api only

you should send it with xhr `xhr.send(form)` or with fetch `fetch(url, {method: 'post', body: form})`

**Comment by alexindigo** [comment]
@kimwandev the code from your example is meant to be ran in nodejs, not in a browser.
And as @jimmywarting there are built in methods available in the browser.

Please feel free to continue conversation here.
