### ISSUE TITLE
Using form-data with typed-rest-client

### ISSUE THREAD

**Issue by mmajcica** [form-data/form-data#410]
Dear,

I'm planning to upload a file base on multipart/form-data specs. I found your library and I'm curious how to use it in my typescript application. I'm using typed-rest-client for all of my http calls.
I suppose I could leverage the uploadStream method from the rest client in order to integrate with form-data.

```
    public async uploadStream<T>(verb: string,
        requestUrl: string,
        stream: NodeJS.ReadableStream,
        options?: IRequestOptions): Promise<IRestResponse<T>> {

        let url: string = util.getUrl(requestUrl, this._baseUrl);
        let headers: ifm.IHeaders = this._headersFromOptions(options, true);

        let res: httpm.HttpClientResponse = await this.client.sendStream(verb, url, stream, headers);
        return this._processResponse<T>(res, options);
    }
```

Is there an example on how to achieve something like this?

Thanks

**Comment by mmajcica** [comment]
To make the question simpler, is there a way to get a NodeJS.ReadableStream from the form-data object?

Thanks

**Comment by alexindigo** [comment]
FormData instance is a Readable stream.
https://github.com/form-data/form-data/blob/master/lib/form_data.js#L16

As for the example, do you mind to simplify it for those without TS tooth? Kinda hard to read. :)

**Comment by mmajcica** [comment]
Indeed it is. I have tried to call the above method in the following way:

```
        let options: IRestRequestOptions = <IRestRequestOptions>{};
        options.additionalHeaders = formData.getHeaders();

        await this.client.uploadStream('POST', url, formData, options);
```

But it was failing. It turns out that the formData is a stream and that is all good. The problem was in the header.

In the typed-rest-client library the following is done over the headers:

` headers["Content-Type"] = headers["Content-Type"] || 'application/json; charset=utf-8';`

and form-data brings back content-type, thus, case sensitive check, this is not found and the right header is not picked up.

The following works well and I'll check for a more elegant solution later (suggestion are welcome considering mine reduced experience with js):

```
        let headers = formData.getHeaders();
        let options: IRestRequestOptions = <IRestRequestOptions>{};
        options.additionalHeaders = { "Content-Type": headers['content-type']};
        
        await this.client.uploadStream('POST', url, formData, options);
```

Would it be a suggestion to change the key in the getHeaders function to return "Content-Type", considering also that that is what the RFC is specifying https://tools.ietf.org/html/rfc7231#section-3.1.1.5 ?

**Comment by alexindigo** [comment]
Looks like you're trying to use it as a Promise, not as a Stream.
FormData is Readable Stream, not a Promise.
This is example from one of the tests:
https://github.com/form-data/form-data/blob/master/test/integration/test-pipe.js#L64-L71

PS. If you keep TypeScript out of your examples, they'd be easier to understand, and more help you'd be able to get from the community.

**Comment by mmajcica** [comment]
I'm sorry about TS, I'll try further on to stick to plain JS.
FormData is a Readable Stream and it all works as written above. My uploadStream function returns a Promise and as such can be "awaited". The third param of my function expects a Readable Stream and if I pass in the instance of FormData object, it all works perfectly.

The only issue that I have found is in the low case content-type header name, and all additional headers that are passed in the form-data object are returned as lower case, https://github.com/form-data/form-data/blob/b16916a568a0d06f3f8a16c31f9a8b89b7844094/lib/form_data.js#L296
and
https://github.com/form-data/form-data/blob/b16916a568a0d06f3f8a16c31f9a8b89b7844094/lib/form_data.js#L301

However, after thinking a bit around that, I'll make a PR for typed-rest-client (https://github.com/Microsoft/typed-rest-client) library so that the check it does here https://github.com/Microsoft/typed-rest-client/blob/7186708f6f5ed96c6c5ca204405915595d5b2149/lib/RestClient.ts#L171

are not case sensitive.
