### ISSUE TITLE
@types/form-data: Property 'getBuffer' does not exist on type 'FormData'

### ISSUE THREAD

**Issue by tabeth** [form-data/form-data#427]
The new property on `FormData`, `getBuffer` isn't properly typed in TypeScript. 

The [latest types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/form-data/index.d.ts) are the following:
```typescript
declare class FormData extends stream.Readable {
    append(key: string, value: any, options?: FormData.AppendOptions | string): void;
    getHeaders(): FormData.Headers;
    submit(params: string | FormData.SubmitOptions, callback?: (error: Error | undefined, response: http.IncomingMessage) => void): http.ClientRequest;
    getBoundary(): string;
    getLength(callback: (err: Error | undefined, length: number) => void): void;
    getLengthSync(): number;
    hasKnownLength(): boolean;
}
```

We need it to look like the following:
```typescript
declare class FormData extends stream.Readable {
    append(key: string, value: any, options?: FormData.AppendOptions | string): void;
    getHeaders(): FormData.Headers;
    getBuffer(): Buffer;
    submit(params: string | FormData.SubmitOptions, callback?: (error: Error | undefined, response: http.IncomingMessage) => void): http.ClientRequest;
    getBoundary(): string;
    getLength(callback: (err: Error | undefined, length: number) => void): void;
    getLengthSync(): number;
    hasKnownLength(): boolean;
}
```

If there isn't already a pull request open in DefinitelyTyped I can create one.

**Comment by alexindigo** [comment]
Thanks @tabeth. Do you want to bring types into the project, so next time we'd update all things at once? Thank you.

**Comment by mapleeit** [comment]
Hi, @tabeth 

I already made a PR to @types/form-data https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36309

Still waiting for merging though.

---

@alexindigo I'm happy to do that.

**Comment by alexindigo** [comment]
@mapleeit That would be awesome! 🙏

**Comment by tabeth** [comment]
@mapleeit you beat me to the punch. I was going to take care of that this weekend. Thanks so much!
