### ISSUE TITLE
types for constructor are incomplete

### ISSUE THREAD

**Issue by rokerkony** [form-data/form-data#443]
hey,
after upgrade to `2.5.*` the types are disallowing to pass specific stream options via constructor, e.g.:
```ts
const formData: FormData = new FormData({
    encoding: file.encoding,
    objectMode: true,
});
```

If I'm correct it should extend the constructor from `stream.Readable`...

**Comment by mapleeit** [comment]
Yes. Seems that you are right. PR welcome!
