### ISSUE TITLE
formData object does not have methods

### ISSUE THREAD

**Issue by mohammedSlimani** [form-data/form-data#444]
I wanted to use the formData in my React Native Application to send a file. The code to do this is really simple:
```
import FormData from 'form-data';

const uploadFile = ()=> {
    const form = new FormData();
    console.log('headers', form.getHeaders()) // Will throw TypeError: form.getHeaders is not a function
}
```
form.append works.
when I console.log(form) I get this:
```
FormData_parts: (8) [Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2)]__proto__: Object

```
Apparently Everything is saved under the _parts and as an Array.

when I console.log(FormData) I get this:
```
ƒ FormData() {
      _classCallCheck(this, FormData);

      this._parts = [];
    }
```
I get the same issue when I am trying to use other functions like form.getBoundary() 
I have been stuck for 3 days now. I don't know where is the problem

**Comment by mohammedSlimani** [comment]
This is not an issue! I found out it work this way.

**Comment by rizowski** [comment]
@mohammedSlimani What did you do to get it to work? I am running into this issue today and have been for a while.

**Comment by mohammedSlimani** [comment]
@rizowski  try to stringify the nested objects that you have inside your data form. For me it was a nested location object, once I did that it worked well!
