### ISSUE TITLE
How to use multipart/form-data instead of application/x-www-form-urlencoded ?

### ISSUE THREAD

**Issue by vedmant** [form-data/form-data#458]
How to force multipart/form-data instead of application/x-www-form-urlencoded when using just few text values? Here is example of my code and it produces application/x-www-form-urlencoded but the API backend I'm trying to use requires "multipart/form-data". Couldn't find info in docs about it.

```
  const axios = require('axios')
  const FormData = require('form-data')

  const form = new FormData()
  form.append('key', key)
  form.append('project', project)
  form.append('urls', url)

  const resp = await axios.post('https://site.com/api', form)
```

**Comment by vedmant** [comment]
Looks like this is Axios specific issue, moved to "got" and it works perfectly.

```
  const got = require('got')
  const FormData = require('form-data')

  const form = new FormData()
  form.append('key', key)
  form.append('project', project)
  form.append('urls', url)

   const resp = await got.post('https://site.com/api', {
      body: form,
   })
```

**Comment by jeoy** [comment]
Axios should set header manually to fix this issue
```
   headers: {
            'content-type': `multipart/form-data; boundary=${form.getBoundary()}`,
    },
```
or 

```
   headers: {
          'content-type': `multipart/form-data; boundary=${form._boundary}`,Ï
    },
```

> Looks like this is Axios specific issue, moved to "got" and it works perfectly.
> 
> ```
>   const got = require('got')
>   const FormData = require('form-data')
> 
>   const form = new FormData()
>   form.append('key', key)
>   form.append('project', project)
>   form.append('urls', url)
> 
>    const resp = await got.post('https://site.com/api', {
>       body: form,
>    })
> ```
