### ISSUE TITLE
Feature request: ability to set boundary string

### ISSUE THREAD

**Issue by C-Saunders** [form-data/form-data#464]
This would enable users to have deterministic request payloads if they need them.

The use-case I have in mind is recording and replay of network interactions with tools like [nock](https://github.com/nock/nock). This doesn't seem to be possible with nondeterministic payloads (or it might be possible with some heavy-duty workarounds).

Edit: ~I should add that this _seems_ fairly straightforward, so I'd be happy to make a pull request for it.~ Pull request made!

**Comment by kjona** [comment]
I have exactly this use case - thanks for your initiative and PR. Currently, I worked around with local type definition and accessing internal values, but obviously, this ability would be a lot better.
