### ISSUE TITLE
index.d.ts doesn't have several methods.

### ISSUE THREAD

**Issue by tylerlong** [form-data/form-data#465]
[index.d.ts](https://github.com/form-data/form-data/blob/master/index.d.ts) doesn't have methods added in this PR: https://github.com/form-data/form-data/pull/408/files

- get
- getAll
- delete 
- has
- set

**Comment by C-Saunders** [comment]
It looks to me like that PR was closed without merged and those methods don't exist on master. Do you see something I'm missing?

**Comment by tylerlong** [comment]
@C-Saunders You are correct!
