### ISSUE TITLE
files are not submitted in node 14

### ISSUE THREAD

**Issue by puzrin** [form-data/form-data#476]
I see strange behaviour for attached files (both streams & Buffers). Those are ok in node.js up to 13, but ignored in node.js 14.

The same with `.submit()`, `node-fech`, `got` and so on.

Could you check?

**Comment by SMKH-PRO** [comment]
Hello @puzrin  did you find any solution?

The same is happening with me, the files are not being submitted, 
https://stackoverflow.com/questions/64360831/upload-multiple-images-from-nodejs-to-php-server

**Comment by puzrin** [comment]
no

**Comment by puzrin** [comment]
Seems node 14 fixed at some moment. Not a problem anymore (at least, `supertest` works).
