### ISSUE TITLE
How to use FormData in ES6 syntax?

### ISSUE THREAD

**Issue by gsofter** [form-data/form-data#484]
I have tried to run following code
```typescript
import FormData from 'form-data'
...
const formData = new FormData();
formData.append('chart', chartfile)
...
```

Unfortunately, I get a error like below
`form_data_1.default is not a constructor`

Let me know where the issue come from.

**Comment by StefanoMartella** [comment]
Hi, Same here. Have you found a solution?

**Comment by Nowadays** [comment]
You've got a bundler ?

The exact same code works in a node env.

**Comment by Swordword** [comment]
I also got same error in electron , is there a solution? thanks

**Comment by thazinwin** [comment]
You would use as `import * as FormData from 'form-data'` to access all modules in a single variable.

**Comment by tyurin-ilya** [comment]
For me this is what worked: import { default as FormData } from "form-data";

**Comment by rgmiranda** [comment]
In my case, `import FormData = require('form-data');` got me out of this. I'm working with TS though.

**Comment by kafir-coder** [comment]
> In my case, `import FormData = require('form-data');` got me out of this. I'm working with TS though.

Thanks!!

**Comment by silasoli** [comment]
> No meu caso, `import FormData = require('form-data');`me tirou disso. Mas estou trabalhando com TS.

bro, thank you very much!
