### ISSUE TITLE
setBoundary and NPM

### ISSUE THREAD

**Issue by fourwadu** [form-data/form-data#491]
Hey, love the package. Just one thing, I don't believe that the latest update that added `setBoundary` is published to npm yet, and that caused some confusion. Would be great if that could be resolved.

Thanks!

**Comment by wandefou** [comment]
I have the same needs , Please help solve it , Thanks a lot!

**Comment by Seia-Soto** [comment]
Also, I am in same situation. Still the release is stuck at v3.0.0. If some maintainer of npm package see this, I hope you to release new version.

**Comment by niftylettuce** [comment]
I'm now a maintainer.  v3.0.1 released https://github.com/form-data/form-data/releases/tag/v3.0.1

**Comment by fourwadu** [comment]
Thank you @niftylettuce.
