### ISSUE TITLE
Is there a breaking change in v4.0.0?

### ISSUE THREAD

**Issue by amio** [form-data/form-data#499]
Hi @niftylettuce , thank you working on this project ❤️

I see you cut a new version 4.0.0 instead of 3.1.0 (#483), is there a breaking change in this release?

**Comment by niftylettuce** [comment]
please defer to https://github.com/form-data/form-data/releases for changelog

**Comment by amio** [comment]
Does this follow [Semantic Versioning](https://semver.org/)?
