### ISSUE TITLE
@types/node should be a dependency or peer dependency since it is referenced in index.d.ts

### ISSUE THREAD

**Issue by mprast** [form-data/form-data#505]
This package is breaking when compiled with Typescript using yarn v2's PnP: 

```
../../root/.yarn/berry/cache/form-data-npm-2.5.1-47256351b5-7.zip/node_modules/form-data/index.d.ts:6:23 - error TS2688: Cannot find type definition file for 'node'.

/// <reference types="node" />
```

yarn v2 only allows a package to import modules explicitly listed as dependencies in package.json. @types/node needs to be listed there before typescript will be able to find the appropriate types.

**Comment by ljharb** [comment]
It shouldn't be a runtime dep, and adding a peer dep is a breaking change. With proper node module resolution, you can import anything that's on disk.
