### ISSUE TITLE
toString is returning "[object FormData]" instead of stringified data

### ISSUE THREAD

**Issue by ShivamS136** [form-data/form-data#515]
I am new to this package but as the name and signature suggest, `toString` should return a stringified value like JSON for the FormData but it is returning the string `[object FormData]`.

I have created [a repl](https://replit.com/@shivams136/FormDatatoString#index.js) for it.

```js
const FormData =  require("form-data");

var data = new FormData();
data.append("modid", "IM");
data.append("token", "provider");
data.append("cat_type", "3");

console.log(data.toString()) //[object FormData]
```

**Comment by octet-stream** [comment]
This method should just return `[object FormData]`. I have tested it in Chrome, Safari and Firefox.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/7884558/132883471-d070d996-9b05-40c6-a622-e4964fb2378d.png)

</details>

**Comment by ShivamS136** [comment]
@octet-stream 
So, is this output `[object FormData]` correct? if yes, then how to use it to print on the console or in logs.

**Comment by ShivamS136** [comment]
I checked the definition of the function and it's just a static string in the return statement, it can't be intended, we need to resolve this.

```js
function () {
  return '[object FormData]';
}
```

![image](https://user-images.githubusercontent.com/32218762/134857262-6531a219-1779-4d63-a1d8-0000915dc23b.png)

**Comment by ShivamS136** [comment]
I have created [a workaround solution](https://replit.com/@shivams136/ConvertFormdatatoJSON#index.js) but this is not 100% correct, This is very useful feature, should be added to the library:

```js
const FormData = require("form-data");

var data = new FormData();
data.append("modid", "IM");
data.append("token", "provider");
data.append("cat_type", "3");

const objectifyFormdata = (data) => {
	return data
		.getBuffer()
		.toString()
		.split(data.getBoundary())
		.filter((e) => e.includes("form-data"))
		.map((e) =>
			e
				.replace(/[\-]+$/g, "")
				.replace(/^[\-]+/g, "")
				.match(/\; name\=\"([^\"]+)\"(.*)/s)
				.filter((v, i) => i == 1 || i == 2)
				.map((e) => e.trim())
		)
		.reduce((acc, cur) => {
			acc[cur[0]] = cur[1];
			return acc;
		}, {});
};

console.log(objectifyFormdata(data));
```

**Comment by octet-stream** [comment]
> if yes, then how to use it to print on the console or in logs.

Normally [`FormData is an iterable object`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries), so if you need to output everything from it, you'll need to:

```js
console.log(Object.fromEntries(form)) // FormData has `Symbol.iterator` method, so you don't have to call `.entries()` directly
```

Where's `form` is an instance of FormData.

If you need to get the data associated with an individual key, you have [`.get()`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/get) and [`.getAll()`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/getAll) methods. However, this package does not have such methods. It is not spec-compliant. You can't get the data from it as you normally would in browsers.

> I have created a workaround solution but this is not 100% correct, This is very useful feature, should be added to the library

Here is the definition of the FormData interface, I can't see they implement toString in such a way: https://xhr.spec.whatwg.org/#interface-formdata

It basically re-used from the [`Object.prototype.toString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString). The default behaviour of this function is just return an `[object type]` string.

> Every object has a toString() method that is automatically called when the object is to be represented as a text value or when an object is referred to in a manner in which a string is expected. **By default, the toString() method is inherited by every object descended from Object. If this method is not overridden in a custom object, toString() returns "[object type]", where type is the object type.**

See description section of the toString method: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString#description

**Comment by ShivamS136** [comment]
Thanks a lot for explaining this,
As far as I could understand that this package doesn't intend to implement the `toString()` in a way to return stringified data. If I want that I'll need to install the other packages mentioned. So it's not an issue but an intended unimplemented feature.
So I'll try to use the `formdata-node`, package mentioned.
Please correct me if I am wrong. 

Also, can you please refer to any source explaining what is **spec-compliant** implementation, I have no clue about that?

**Comment by octet-stream** [comment]
> Also, can you please refer to any source explaining what is spec-compliant implementation, I have no clue about that?

There's the [FormData specification](https://xhr.spec.whatwg.org/#interface-formdata). It defines the shape of FormData interface and how it should behave. Every modern browser implements it, at least majors (you can open a console and find it on `globalThis`, or `window`). Mentioned libraries implement this spec too, meaning that they spec-compliant.

**Comment by ShivamS136** [comment]
OK, Thanks @octet-stream for the knowledge sharing, Closing this issue here.
