### ISSUE TITLE
Move away from `util.isArray`

### ISSUE THREAD

**Issue by marco-ippolito** [form-data/form-data#563]
With the new Node.js 22 release, we have runtime deprecated `util.isArray` and in node 23 we plan to completely remove it.
https://github.com/form-data/form-data/blob/53adbd81e9bde27007b28083068f2fc8272614dc/lib/form_data.js#L64
This line of code will cause failure in consumers of this package like `fastify`.
https://github.com/nodejs/node/pull/52744#issuecomment-2084502595
I'll create a PR to help migrating `util.isArray` to `Array.isArray`

**Comment by ljharb** [comment]
@jkoenig134 that's not how issues work on github; they're closed when the fix is merged.

**Comment by ljharb** [comment]
I have now published a patch to the v2, v3, and v4 release lines.
