### ISSUE TITLE
(node:29052) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.

### ISSUE THREAD

**Issue by cmhleveret** [form-data/form-data#567]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `form-data@3.0.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/form-data/lib/form_data.js b/node_modules/form-data/lib/form_data.js
index cf836b0..9316442 100644
--- a/node_modules/form-data/lib/form_data.js
+++ b/node_modules/form-data/lib/form_data.js
@@ -60,7 +60,7 @@ FormData.prototype.append = function(field, value, options) {
   }
 
   // https://github.com/felixge/node-form-data/issues/38
-  if (util.isArray(value)) {
+  if (Array.isArray(value)) {
     // Please convert your array into string
     // the way web server expects it
     this._error(new Error('Arrays are not supported.'));
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Pnlvfx** [comment]
I've seen the commit with this fix, when will it be released on npm?

**Comment by ljharb** [comment]
Fixed in #564.

**Comment by Pnlvfx** [comment]
> Fixed in #564.

Yes but it has not been released on npm

**Comment by Pnlvfx** [comment]
I've just marked it because I was asking before about the release, I'm patient, don't worry.

**Comment by ljharb** [comment]
I have now published a patch to the v2, v3, and v4 release lines.
