### ISSUE TITLE
Can't set file encoding in options

### ISSUE THREAD

**Issue by rodrigok** [form-data/form-data#78]
I can't set any other headers for file like file encoding. Maybe use the property options to pass some headers allows more flexibility.

**Comment by DylanPiercey** [comment]
@rodrigok what header are you trying to set and what would be your expected (example) output formdata string?

**Comment by rodrigok** [comment]
@DylanPiercey, sorry I can't remember, was 1 year ago :(

**Comment by alexindigo** [comment]
Ok, let us know if you have further questions. Closing.
