### ISSUE TITLE
hanle Content-dispostion in request

### ISSUE THREAD

**Issue by kareka** [form-data/form-data#82]
am trying to test a service which does file upload .and below is the sample data captured by fiddler.how i can handle this in form-data
-----------------------------7de3c303c07ba
 Content-Disposition: form-data; name="slow"

5000
 -----------------------------7de3c303c07ba
 Content-Disposition: form-data; name="file"; filename="short.csv"
 Content-Type: application/vnd.ms-excel

user,password,post
xyz@xx.com,abcde,afdfd

**Comment by alexindigo** [comment]
Hey can you elaborate on your question? And maybe throw in pieces of code too? Thank you.

**Comment by alexindigo** [comment]
I'll close it for now. Let me know if your have more questions/details.
